-- Script de inicialização Firebird para Docker
-- Cria as tabelas necessárias para diferentes clientes

-- Cria a tabela ghas_tbl_pac_agendados
CREATE TABLE ghas_tbl_pac_agendados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_paciente VARCHAR(100) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(100),
    data_consulta TIMESTAMP NOT NULL,
    nome_medico VARCHAR(100),
    especialidade VARCHAR(100),
    status VARCHAR(20) DEFAULT 'PENDENTE' CHECK (status IN ('PENDENTE', 'CONFIRMADO', 'CANCELADO', 'SEM_RESPOSTA')),
    
    -- Campos de controle para Botconversa
    subscriber_id INTEGER UNIQUE,
    mensagem_enviada BLOB SUB_TYPE TEXT,
    resposta_paciente VARCHAR(10),
    interpretacao_resposta VARCHAR(50),
    respondido_em TIMESTAMP,
    
    -- Controle de frequência de lembretes
    lembrete_48h_enviado SMALLINT DEFAULT 0 CHECK (lembrete_48h_enviado IN (0,1)),
    lembrete_12h_enviado SMALLINT DEFAULT 0 CHECK (lembrete_12h_enviado IN (0,1)),
    ultimo_lembrete_enviado TIMESTAMP,
    tipo_ultimo_lembrete VARCHAR(10),
    
    -- Campo obrigatório para número sequencial da agenda
    nr_seq_agenda INTEGER NOT NULL,
    
    -- Timestamps
    enviado_em TIMESTAMP,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Cria índices para melhor performance
CREATE INDEX idx_ghas_tbl_pac_agendados_subscriber_id ON ghas_tbl_pac_agendados(subscriber_id);
CREATE INDEX idx_ghas_tbl_pac_agendados_status ON ghas_tbl_pac_agendados(status);
CREATE INDEX idx_ghas_tbl_pac_agendados_data_consulta ON ghas_tbl_pac_agendados(data_consulta);
CREATE INDEX idx_ghas_tbl_pac_agendados_telefone ON ghas_tbl_pac_agendados(telefone);
CREATE INDEX idx_ghas_tbl_pac_agendados_nr_seq_agenda ON ghas_tbl_pac_agendados(nr_seq_agenda);

-- Cria sequência para ID (Firebird 2.5 e anteriores)
CREATE GENERATOR ghas_tbl_pac_agendados_gen;
SET GENERATOR ghas_tbl_pac_agendados_gen TO 0;

-- Insere dados de exemplo
INSERT INTO ghas_tbl_pac_agendados (
    id,
    nome_paciente, 
    telefone, 
    email, 
    data_consulta, 
    nome_medico, 
    especialidade,
    nr_seq_agenda
) VALUES 
    (GEN_ID(ghas_tbl_pac_agendados_gen, 1), 'João Silva', '5511999999999', 'joao@email.com', DATEADD(DAY, 3, CURRENT_TIMESTAMP), 'Dr. Carlos', 'Cardiologia', 1001);

INSERT INTO ghas_tbl_pac_agendados (
    id,
    nome_paciente, 
    telefone, 
    email, 
    data_consulta, 
    nome_medico, 
    especialidade,
    nr_seq_agenda
) VALUES 
    (GEN_ID(ghas_tbl_pac_agendados_gen, 1), 'Maria Santos', '5511888888888', 'maria@email.com', DATEADD(DAY, 2, CURRENT_TIMESTAMP), 'Dra. Ana', 'Dermatologia', 1002);

-- Comentários para documentação (Firebird não suporta COMMENT ON, mas mantemos para referência)
-- Tabela: ghas_tbl_pac_agendados - Tabela de atendimentos médicos com controle de confirmação via WhatsApp
-- Coluna: subscriber_id - ID do subscriber no Botconversa
-- Coluna: status - Status da confirmação da consulta
-- Coluna: nr_seq_agenda - Número sequencial da agenda (campo obrigatório)
