-- Script de inicialização Oracle para Docker
-- Cria as tabelas no owner atual (fornecido pelo cliente)

-- Cria a tabela atendimentos no owner atual
CREATE TABLE atendimentos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_paciente VARCHAR2(100) NOT NULL,
    telefone VARCHAR2(20) NOT NULL,
    email VARCHAR2(100),
    data_consulta TIMESTAMP NOT NULL,
    nome_medico VARCHAR2(100),
    especialidade VARCHAR2(100),
    status_confirmacao VARCHAR2(20) DEFAULT 'PENDENTE' CHECK (status_confirmacao IN ('PENDENTE', 'CONFIRMADO', 'CANCELADO', 'SEM_RESPOSTA')),
    
    -- Campos de controle para Botconversa
    subscriber_id NUMBER UNIQUE,
    mensagem_enviada CLOB,
    resposta_paciente VARCHAR2(10),
    respondido_em TIMESTAMP,
    
    -- Controle de frequência de lembretes
    lembrete_48h_enviado NUMBER(1) DEFAULT 0 CHECK (lembrete_48h_enviado IN (0,1)),
    lembrete_12h_enviado NUMBER(1) DEFAULT 0 CHECK (lembrete_12h_enviado IN (0,1)),
    ultimo_lembrete_enviado TIMESTAMP,
    tipo_ultimo_lembrete VARCHAR2(10),
    
    -- Timestamps
    criado_em TIMESTAMP DEFAULT SYSTIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Cria índices para melhor performance
CREATE INDEX idx_atendimentos_subscriber_id ON atendimentos(subscriber_id);
CREATE INDEX idx_atendimentos_status ON atendimentos(status_confirmacao);
CREATE INDEX idx_atendimentos_data_consulta ON atendimentos(data_consulta);
CREATE INDEX idx_atendimentos_telefone ON atendimentos(telefone);

-- Cria sequência para ID (Oracle 11g e anteriores)
CREATE SEQUENCE atendimentos_seq START WITH 1 INCREMENT BY 1;

-- Insere dados de exemplo
INSERT INTO atendimentos (
    id,
    nome_paciente, 
    telefone, 
    email, 
    data_consulta, 
    nome_medico, 
    especialidade
) VALUES 
    (atendimentos_seq.NEXTVAL, 'João Silva', '5511999999999', 'joao@email.com', SYSTIMESTAMP + INTERVAL '3' DAY, 'Dr. Carlos', 'Cardiologia');

INSERT INTO atendimentos (
    id,
    nome_paciente, 
    telefone, 
    email, 
    data_consulta, 
    nome_medico, 
    especialidade
) VALUES 
    (atendimentos_seq.NEXTVAL, 'Maria Santos', '5511888888888', 'maria@email.com', SYSTIMESTAMP + INTERVAL '2' DAY, 'Dra. Ana', 'Dermatologia');

-- Comentários para documentação
COMMENT ON TABLE atendimentos IS 'Tabela de atendimentos médicos com controle de confirmação via WhatsApp';
COMMENT ON COLUMN atendimentos.subscriber_id IS 'ID do subscriber no Botconversa';
COMMENT ON COLUMN atendimentos.status_confirmacao IS 'Status da confirmação da consulta';

-- Commit das alterações
COMMIT;
