-- Script de inicialização Firebird para Docker
-- Cria as tabelas necessárias para o sistema

-- Cria a tabela atendimentos
CREATE TABLE atendimentos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_paciente VARCHAR(100) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(100),
    data_consulta TIMESTAMP NOT NULL,
    nome_medico VARCHAR(100),
    especialidade VARCHAR(100),
    status_confirmacao VARCHAR(20) DEFAULT 'PENDENTE' CHECK (status_confirmacao IN ('PENDENTE', 'CONFIRMADO', 'CANCELADO', 'SEM_RESPOSTA')),
    
    -- Campos de controle para Botconversa
    subscriber_id INTEGER UNIQUE,
    mensagem_enviada BLOB SUB_TYPE TEXT,
    resposta_paciente VARCHAR(10),
    respondido_em TIMESTAMP,
    
    -- Controle de frequência de lembretes
    lembrete_48h_enviado SMALLINT DEFAULT 0 CHECK (lembrete_48h_enviado IN (0,1)),
    lembrete_12h_enviado SMALLINT DEFAULT 0 CHECK (lembrete_12h_enviado IN (0,1)),
    ultimo_lembrete_enviado TIMESTAMP,
    tipo_ultimo_lembrete VARCHAR(10),
    
    -- Timestamps
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Cria índices para melhor performance
CREATE INDEX idx_atendimentos_subscriber_id ON atendimentos(subscriber_id);
CREATE INDEX idx_atendimentos_status ON atendimentos(status_confirmacao);
CREATE INDEX idx_atendimentos_data_consulta ON atendimentos(data_consulta);
CREATE INDEX idx_atendimentos_telefone ON atendimentos(telefone);

-- Cria sequência para ID (Firebird 2.5 e anteriores)
CREATE GENERATOR atendimentos_gen;
SET GENERATOR atendimentos_gen TO 0;

-- Insere dados de exemplo
INSERT INTO atendimentos (
    id,
    nome_paciente, 
    telefone, 
    email, 
    data_consulta, 
    nome_medico, 
    especialidade
) VALUES 
    (GEN_ID(atendimentos_gen, 1), 'João Silva', '5511999999999', 'joao@email.com', DATEADD(DAY, 3, CURRENT_TIMESTAMP), 'Dr. Carlos', 'Cardiologia');

INSERT INTO atendimentos (
    id,
    nome_paciente, 
    telefone, 
    email, 
    data_consulta, 
    nome_medico, 
    especialidade
) VALUES 
    (GEN_ID(atendimentos_gen, 1), 'Maria Santos', '5511888888888', 'maria@email.com', DATEADD(DAY, 2, CURRENT_TIMESTAMP), 'Dra. Ana', 'Dermatologia');

-- Comentários para documentação (Firebird não suporta COMMENT ON, mas mantemos para referência)
-- Tabela: atendimentos - Tabela de atendimentos médicos com controle de confirmação via WhatsApp
-- Coluna: subscriber_id - ID do subscriber no Botconversa
-- Coluna: status_confirmacao - Status da confirmação da consulta
