-- Script de inicialização Oracle para Docker
-- Cria as tabelas necessárias para diferentes clientes

-- Cria a tabela ghas_tbl_pac_agendados
CREATE TABLE ghas_tbl_pac_agendados (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_paciente VARCHAR2(100) NOT NULL,
    telefone VARCHAR2(20) NOT NULL,
    email VARCHAR2(100),
    data_consulta TIMESTAMP NOT NULL,
    nome_medico VARCHAR2(100),
    especialidade VARCHAR2(100),
    status VARCHAR2(20) DEFAULT 'PENDENTE' CHECK (status IN ('PENDENTE', 'CONFIRMADO', 'CANCELADO', 'SEM_RESPOSTA')),
    
    -- Campos de controle para Botconversa
    subscriber_id NUMBER UNIQUE,
    mensagem_enviada CLOB,
    resposta_paciente VARCHAR2(10),
    interpretacao_resposta VARCHAR2(50),
    respondido_em TIMESTAMP,
    
    -- Controle de frequência de lembretes
    lembrete_48h_enviado NUMBER(1) DEFAULT 0 CHECK (lembrete_48h_enviado IN (0,1)),
    lembrete_12h_enviado NUMBER(1) DEFAULT 0 CHECK (lembrete_12h_enviado IN (0,1)),
    ultimo_lembrete_enviado TIMESTAMP,
    tipo_ultimo_lembrete VARCHAR2(10),
    
    -- Campo obrigatório para número sequencial da agenda
    nr_seq_agenda NUMBER NOT NULL,
    
    -- Timestamps
    enviado_em TIMESTAMP,
    criado_em TIMESTAMP DEFAULT SYSTIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Cria índices para melhor performance
CREATE INDEX idx_ghas_tbl_pac_agendados_subscriber_id ON ghas_tbl_pac_agendados(subscriber_id);
CREATE INDEX idx_ghas_tbl_pac_agendados_status ON ghas_tbl_pac_agendados(status);
CREATE INDEX idx_ghas_tbl_pac_agendados_data_consulta ON ghas_tbl_pac_agendados(data_consulta);
CREATE INDEX idx_ghas_tbl_pac_agendados_telefone ON ghas_tbl_pac_agendados(telefone);
CREATE INDEX idx_ghas_tbl_pac_agendados_nr_seq_agenda ON ghas_tbl_pac_agendados(nr_seq_agenda);

-- Cria sequência para ID (Oracle 11g e anteriores)
CREATE SEQUENCE ghas_tbl_pac_agendados_seq START WITH 1 INCREMENT BY 1;

-- Insere dados de exemplo
INSERT INTO ghas_tbl_pac_agendados (
    id,
    nome_paciente, 
    telefone, 
    email, 
    data_consulta, 
    nome_medico, 
    especialidade,
    nr_seq_agenda
) VALUES 
    (ghas_tbl_pac_agendados_seq.NEXTVAL, 'João Silva', '5511999999999', 'joao@email.com', SYSTIMESTAMP + INTERVAL '3' DAY, 'Dr. Carlos', 'Cardiologia', 1001);

INSERT INTO ghas_tbl_pac_agendados (
    id,
    nome_paciente, 
    telefone, 
    email, 
    data_consulta, 
    nome_medico, 
    especialidade,
    nr_seq_agenda
) VALUES 
    (ghas_tbl_pac_agendados_seq.NEXTVAL, 'Maria Santos', '5511888888888', 'maria@email.com', SYSTIMESTAMP + INTERVAL '2' DAY, 'Dra. Ana', 'Dermatologia', 1002);

-- Comentários para documentação
COMMENT ON TABLE ghas_tbl_pac_agendados IS 'Tabela de atendimentos médicos com controle de confirmação via WhatsApp';
COMMENT ON COLUMN ghas_tbl_pac_agendados.subscriber_id IS 'ID do subscriber no Botconversa';
COMMENT ON COLUMN ghas_tbl_pac_agendados.status IS 'Status da confirmação da consulta';
COMMENT ON COLUMN ghas_tbl_pac_agendados.nr_seq_agenda IS 'Número sequencial da agenda (campo obrigatório)';

-- Commit das alterações
COMMIT;
